import { ApiResource } from './api.models';

export const mockApiResources: ApiResource[] = [
  { id: 1, method: 'GET', path: '/api/users', description: '获取用户列表' },
  { id: 2, method: 'GET', path: '/api/users/:id', description: '获取用户详情' },
  { id: 3, method: 'POST', path: '/api/users', description: '创建用户' },
  { id: 4, method: 'PUT', path: '/api/users/:id', description: '更新用户信息' },
  { id: 5, method: 'DELETE', path: '/api/users/:id', description: '删除用户' },
  { id: 6, method: 'GET', path: '/api/roles', description: '获取角色列表' },
  { id: 7, method: 'GET', path: '/api/roles/:id', description: '获取角色详情' },
  { id: 8, method: 'POST', path: '/api/roles', description: '创建角色' },
  { id: 9, method: 'PUT', path: '/api/roles/:id', description: '更新角色' },
  { id: 10, method: 'DELETE', path: '/api/roles/:id', description: '删除角色' },
  { id: 11, method: 'GET', path: '/api/menus', description: '获取菜单列表' },
  { id: 12, method: 'GET', path: '/api/menus/tree', description: '获取菜单树形结构' },
  { id: 13, method: 'POST', path: '/api/menus', description: '创建菜单' },
  { id: 14, method: 'PUT', path: '/api/menus/:id', description: '更新菜单' },
  { id: 15, method: 'DELETE', path: '/api/menus/:id', description: '删除菜单' },
  { id: 16, method: 'GET', path: '/api/orders', description: '获取订单列表' },
  { id: 17, method: 'GET', path: '/api/orders/:id', description: '获取订单详情' },
  { id: 18, method: 'POST', path: '/api/orders', description: '创建订单' },
  { id: 19, method: 'PUT', path: '/api/orders/:id', description: '更新订单' },
  { id: 20, method: 'GET', path: '/api/products', description: '获取商品列表' },
  { id: 21, method: 'GET', path: '/api/products/:id', description: '获取商品详情' },
  { id: 22, method: 'POST', path: '/api/products', description: '创建商品' },
  { id: 23, method: 'PUT', path: '/api/products/:id', description: '更新商品' },
  { id: 24, method: 'DELETE', path: '/api/products/:id', description: '删除商品' },
  { id: 25, method: 'GET', path: '/api/reports/sales', description: '销售报表' },
  { id: 26, method: 'GET', path: '/api/reports/users', description: '用户报表' },
  { id: 27, method: 'GET', path: '/api/logs/operation', description: '操作日志' },
  { id: 28, method: 'GET', path: '/api/logs/access', description: '访问日志' },
];